### ISSUE TITLE
Suggestion: Add categories ”no_std“ and maybe “embedded” to Cargo.toml

### ISSUE THREAD

**Issue by thecodechemist99** [braincore/pid-rs#16]
Hi,

it would be great if you could add the category `"no-std"` (and maybe also `"embedded"`) to the `Cargo.toml` file of your crate. Adding these categories would make it a lot easier to find for embedded developers on [crates.io](https://crates.io) using filter by category. Right now, your crate is excluded from the filtered results despite being compatible.

It would look like this:
```
[package]
categories = ["no-std", "embedded"]
```

**Comment by Owez** [comment]
Agreed, I'll add later today or tomorrow and publish with #17 all going well

**Comment by Owez** [comment]
I've looked through all the category slugs and the two here seem like the most fitting. Maybe `algorithms` could count as well because this controller is fundementally an algorithm?
