### ISSUE TITLE
Possible enhancements: Feedforward and Limit Bugfix

### ISSUE THREAD

**Issue by harrisonmg** [braincore/pid-rs#17]
Hello,

I've recently been using this library for some motor control. Thanks for your work!

For my own purposes, I added a simple linear feedforward term to the controller.

I also fixed a small bug with the term and output limits: giving a negative limit causes the term or output to be clamped to the limit value.

Would you be interested in pull requests for one or both of these items?

**Comment by Owez** [comment]
Yep if you could make a PR for the bug that'd be great. If the feedforward is an optional extra (e.g. `.feedforward(x)`) on the controller it should be a nice addition, probably best to make that a seperate PR :)

I'm not sure about the intricacies of feedforwards, I'll have to have a look into it
