### ISSUE TITLE
Version 2.2 is not semver-compatible

### ISSUE THREAD

**Issue by hannobraun** [braincore/pid-rs#7]
Version 2.2 shares the major version number (`2`) with the previous version, 2.1. That means, as far as Cargo (which follows semantic versioning) is concerned, this is a compatible release that will be picked automatically on every `cargo update`, or for new builds where no `Cargo.lock` is present (even if `Cargo.toml` explicitly specifies `pid = "2.1.0"`).

However, 2.2 is not a compatible release. The new argument to `Pid::new` is a breaking change, and I think this change will break every user of `pid`. This is not a problem for me personally, as I just use `pid` in an application that has a lock file checked into the repository and thus have full control over when I update. I wanted to make you aware of the problem though.

Thanks for your work on pid-rs!

**Comment by braincore** [comment]
Good catch! Sorry, in my rush to publish I overlooked this. I've yanked v2.2.0 from crates.io and republished as v3.0.0. Thanks!
